import os
import time
import random

countryList = [
    'panama',
    'us-west',
    'us-silicon-valley',
    'us-seattle',
    'us-california',
    'us-las-vegas',
    'us-denver',
    'us-houston',
    'us-texas',
    'us-chicago',
    'us-washington-dc',
    'us-east',
    'us-florida',
    'us-new-york',
    'us-atlanta',
    'ca-vancouver',
    'ca-toronto',
    'ca-ontario',
    'ca-montreal',
    'brazil',
    'bahamas',
    'venezuela',
    'mexico',
    'greenland',
    'argentina',
    'mongolia',
    'uk-streaming-optimized',
    'uk-southampton',
    'uk-manchester',
    'uk-london',
    'denmark',
    'netherlands',
    'france',
    'luxembourg',
    'ireland',
    'portugal',
    'de-berlin',
    'de-frankfurt',
    'jp-streaming-optimized',
    'jp-tokyo',
    'spain',
    'isle-of-man',
    'malta',
    'czech-republic',
    'slovakia',
    'belgium',
    'liechtenstein',
    'morocco',
    'new-zealand',
    'switzerland',
    'sweden',
    'albania',
    'italy',
    'norway',
    'monaco',
    'andorra',
    'austria',
    'au-melbourne',
    'au-sydney',
    'au-perth',
    'estonia',
    'romania',
    'finland',
    'iceland',
    'greece',
    'macedonia',
    'egypt',
    'montenegro',
    'ukraine',
    'china',
    'moldova',
    'hong-kong',
    'latvia',
    'croatia',
    'turkey',
    'poland',
    'cyprus',
    'georgia',
    'algeria',
    'bulgaria',
    'kazakhstan',
    'vietnam',
    'bangladesh',
    'cambodia',
    'lithuania',
    'israel',
    'philippines',
    'serbia',
    'armenia',
    'hungary',
    'taiwan',
    'macao',
    'bosnia-and-herzegovina',
    'sri-lanka',
    'singapore',
    'saudi-arabia',
    'india',
    'nigeria',
    'united-arab-emirates',
    'qatar',
    'south-africa'
]


class randomConnect():
    def set_random(self):
        i = random.randint(1, 100)
        os.system('piactl set region ' + countryList[i])

    def connect(self):
        os.system('piactl connect')

    def disconnect(self):
        os.system('piactl disconnect')

